{% set name = "pymc3" %}
{% set version = "3.0" %}
{% set md5 = "fe27a0e72848918500f7d47758184ee9" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  fn:  {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: {{ md5 }}

build:
  number: 0
  skip: True  # [py>35]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    # - numpy >=1.11.0
    # - scipy >=0.12.0
    # - matplotlib >=1.5.0
    # - theano >=0.8.2
    # - pandas >=0.18.0
    # - patsy >=0.4.0
    # - joblib >=0.9
    # - tqdm >=4.8.4
    # - enum43 # [py2k]

  run:
    - python
    - numpy >=1.11.0
    - scipy >=0.12.0
    - matplotlib >=1.5.0
    - theano >=0.8.2
    - pandas >=0.18.0
    - patsy >=0.4.0
    - joblib >=0.9
    - tqdm >=4.8.4
    - enum34  # [py2k]

test:
  imports:
    - pymc3
    - pymc3.backends
    - pymc3.distributions
    - pymc3.examples
    - pymc3.glm
    - pymc3.step_methods
    - pymc3.tests
    - pymc3.tuning
    - pymc3.variational

  requires:
    - nose

about:
  home: http://github.com/pymc-devs/pymc3
  license: AFL-3.0
  summary: 'Probabilistic Programming in Python.'
  license_family: Apache

extra:
  recipe-maintainers:
    - ericmjl
    - springcoil
