{% set version = "3.9.3" %}

package:
  name: pymc3
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pymc3/pymc3-{{ version }}.tar.gz
  sha256: abe046f5a5d0e5baee80b7c4bc0a4c218f61b517b62d77be4f89cf4784c27d78

build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6.1
    - pip
  run:
    - python >=3.6.1
    - theano >=1.0.5
    - numpy >=1.13.0
    - scipy >=0.18.1
    - arviz >=0.9.0,<0.11.2
    - fastprogress >=0.2.0
    - pandas >=0.18.0
    - patsy >=0.5.1
    - tqdm >=4.8.4
    - h5py >=2.7.0
    - typing-extensions >=3.7.4.3,<4
    - contextvars
    - dataclasses

test:
  imports:
    - pymc3
    - pymc3.backends
    - pymc3.distributions
    - pymc3.examples
    - pymc3.glm
    - pymc3.gp
    - pymc3.step_methods
    - pymc3.tests
    - pymc3.tuning
    - pymc3.variational
    - pymc3.ode
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/pymc-devs/pymc3
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: Probabilistic Programming in Python

extra:
  recipe-maintainers:
    - ericmjl
    - springcoil
    - twiecki
    - fonnesbeck
    - michaelosthege
    - maresb
