{% set version = "3.11.4" %}

package:
  name: pymc3
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pymc3/pymc3-{{ version }}.tar.gz
  sha256: 3b88d1e6c85f7fb8a9b99d6f136ac860672170370ec4146338fdd160c3b3fd3f

build:
  number: 1
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
  run:
    - python
    - arviz >=0.11.0
    - cachetools >=4.2.1
    - dill
    - fastprogress >=0.2.0
    - numpy >=1.15.0
    - pandas >=0.24.0
    - patsy >=0.5.1
    - scipy >=1.2.0
    - semver  # We may need to add the pin: >=2.13.0
    - theano-pymc ==1.1.2
    - typing-extensions >=3.7.4
    - cxx-compiler  # [not win]
    - m2w64-toolchain  # [win]
    - libpython  # [win]
    # # For numba explanation, see https://github.com/conda-forge/pymc3-feedstock/pull/70#discussion_r688813190
    # - numba  # [not linux]
    # - h5py >=2.7  # [win]
    # - mkl-service  # [win]
    # - netcdf4  # [win]

test:
  imports:
    - pymc3
    - pymc3.backends
    - pymc3.distributions
    - pymc3.glm
    - pymc3.gp
    - pymc3.step_methods
    - pymc3.tests
    - pymc3.tuning
    - pymc3.variational
    - pymc3.ode
  commands:
    - pip check
    # - set "CXXFLAGS=-fno-asynchronous-unwind-tables"  # [win]
    - pytest pymc3/tests/test_pickling.py
    - pytest -k "not test_spawn_densitydist_mpctxwarning" pymc3/tests/test_parallel_sampling.py
    - pytest pymc3/tests/test_ode.py
    - pytest pymc3/tests/test_ndarray_backend.py
    - pytest pymc3/tests/test_coords.py
    - pytest -k "not test_model_to_graphviz_for_model_with_data_container" pymc3/tests/test_data_container.py
    - pytest -k "not test_weibull" pymc3/tests/test_distributions.py
    - pytest pymc3/tests/test_distributions_random.py
    - pytest pymc3/tests/test_distributions_timeseries.py
    - pytest pymc3/tests/test_distribution_defaults.py
    - pytest pymc3/tests/test_dist_math.py
    - pytest pymc3/tests/test_examples.py
    - pytest pymc3/tests/test_glm.py
    - pytest pymc3/tests/test_gp.py
    - pytest pymc3/tests/test_hmc.py
    - pytest pymc3/tests/test_math.py
    - pytest pymc3/tests/test_minibatches.py
    - pytest pymc3/tests/test_missing.py
    - pytest pymc3/tests/test_mixture.py
    - pytest pymc3/tests/test_model.py
    - pytest pymc3/tests/test_modelcontext.py
    - pytest pymc3/tests/test_models_linear.py
    - pytest pymc3/tests/test_models_utils.py
    - pytest pymc3/tests/test_model_func.py
    - pytest -k "not test_graphviz" pymc3/tests/test_model_graph.py
    - pytest pymc3/tests/test_model_helpers.py
    - pytest pymc3/tests/test_plots.py
    - pytest pymc3/tests/test_posdef_sym.py
    - pytest pymc3/tests/test_posteriors.py
    - pytest pymc3/tests/test_posterior_predictive.py
    - pytest pymc3/tests/test_profile.py
    - pytest pymc3/tests/test_quadpotential.py
    - pytest pymc3/tests/test_random.py
    - pytest pymc3/tests/test_sampling.py
    # - pytest pymc3/tests/test_sampling_jax.py
    - pytest pymc3/tests/test_shape_handling.py
    - pytest pymc3/tests/test_shared.py
    - pytest pymc3/tests/test_smc.py
    - pytest pymc3/tests/test_special_functions.py
    - pytest pymc3/tests/test_starting.py
    - pytest pymc3/tests/test_step.py
    - pytest pymc3/tests/test_theanof.py
    - pytest pymc3/tests/test_tracetab.py
    - pytest pymc3/tests/test_transforms.py
    - pytest pymc3/tests/test_tuning.py
    - pytest pymc3/tests/test_types.py
    - pytest pymc3/tests/test_updates.py
    - pytest pymc3/tests/test_util.py
    - pytest pymc3/tests/test_variational_inference.py

  requires:
    - pip
    - pytest
    # - scipy <1.7.0  # https://github.com/pymc-devs/pymc3/issues/4810#issuecomment-869487376
  source_files:
    - pymc3/tests

about:
  home: http://github.com/pymc-devs/pymc3
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: Probabilistic Programming in Python

extra:
  recipe-maintainers:
    - ericmjl
    - springcoil
    - twiecki
    - fonnesbeck
    - michaelosthege
    - maresb
