{% set version = "3.11.2" %}

package:
  name: pymc3
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pymc3/pymc3-{{ version }}.tar.gz
  sha256: d3b93c8923ae8c8107c5adfd22f7c37fa0849a00a9723e0e0a0ca6afb582d6c3

build:
  number: 4
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - arviz >=0.11.0
    - cachetools >=4.2.1
    - dill
    - fastprogress >=0.2.0
    - numpy >=1.15.0
    - pandas >=0.24.0
    - patsy >=0.5.1
    - scipy >=1.2.0
    - semver
    - theano-pymc ==1.1.2
    - typing-extensions >=3.7.4
    - mkl-service
    - cxx-compiler  # [not win]
    - m2w64-toolchain  # [win]
    - libpython  # [win]

test:
  imports:
    - pymc3
    - pymc3.backends
    - pymc3.distributions
    - pymc3.glm
    - pymc3.gp
    - pymc3.step_methods
    - pymc3.tests
    - pymc3.tuning
    - pymc3.variational
    - pymc3.ode
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/pymc-devs/pymc3
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: Probabilistic Programming in Python

extra:
  recipe-maintainers:
    - ericmjl
    - springcoil
    - twiecki
    - fonnesbeck
    - michaelosthege
    - maresb
