{% set version = "3.5" %}

package:
  name: pymc3
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pymc3/pymc3-{{ version }}.tar.gz
  sha256: 6088e683c6d730bb21350a0f54ee083fa5a28e4d5ef52d57878141c9c20f21ee

build:
  number: 1000
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - numpy >=1.11.0
    - scipy >=0.12.0
    - matplotlib >=1.5.0
    - theano >=0.9
    - pandas >=0.18.0
    - patsy >=0.4.0
    - joblib >=0.9
    - six >=1.10.0
    - tqdm >=4.8.4
    - h5py >=2.7.0
    - enum34 >=1.1.6  # [py<34]

test:
  imports:
    - pymc3
    - pymc3.backends
    - pymc3.distributions
    - pymc3.examples
    - pymc3.glm
    - pymc3.gp
    - pymc3.step_methods
    - pymc3.tests
    - pymc3.tuning
    - pymc3.variational

  requires:
    - pytest

about:
  home: http://github.com/pymc-devs/pymc3
  license: Apache-2.0
  summary: 'Probabilistic Programming in Python.'
  license_family: Apache

extra:
  recipe-maintainers:
    - ericmjl
    - springcoil
