{% set version = "3.11.6" %}

package:
  name: pymc3
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pymc3/pymc3-{{ version }}.tar.gz
  sha256: 9e930a1cfd2ee558892b4d92af043696c65a622b64098332687fd75c78f10bce

build:
  number: 0
  skip: true  # [py>=310]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
  run:
    - python
    # The !=0.13.0 pin is a workaround for:
    # <https://github.com/conda-forge/arviz-feedstock/issues/49>
    - arviz >=0.11.0,!=0.13.0
    - cachetools >=4.2.1
    - deprecat
    - dill
    - fastprogress >=0.2.0
    - numpy >=1.15.0,<1.22.2
    - pandas >=0.24.0,<2.1
    - patsy >=0.5.1
    - scipy >=1.7.3,<1.8.0
    - semver >=2.13.0
    - theano-pymc ==1.1.2
    - typing-extensions >=3.7.4
    - cxx-compiler  # [not win]
    - m2w64-toolchain  # [win]
    - libpython  # [win]

test:
  imports:
    - pymc3
    - pymc3.backends
    - pymc3.distributions
    - pymc3.glm
    - pymc3.gp
    - pymc3.step_methods
    - pymc3.tests
    - pymc3.tuning
    - pymc3.variational
    - pymc3.ode
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/pymc-devs/pymc3
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: Probabilistic Programming in Python

extra:
  recipe-maintainers:
    - ericmjl
    - springcoil
    - twiecki
    - fonnesbeck
    - michaelosthege
    - maresb
