appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: wPsk9JX2VrjXMdRqnkQYlAvV8o/fnhv0u8rC+k2Kv6dR52ZQ6Sakr35m8sEEzb/3zeGit+eBCjSvSVKHdfg20smfY0lKk7sLIzSzNahjPuM7gwxq66KthSudyn2xy2eriuXpHOT4rFNERbaBDcJAps8f97681R25wJg4ZvyR93j7L08eZF7RLcm9D82e0Ei+O7It+bmrTSWYKaNKE+tD0XVeK0fKVd05HeCKwTBBnwUZBKTQkaFHnZsX8rVU+AJDw0FYrBo2lYjBVL2CH6aoFCUyZ2ZmmWPjmjpb7uOPTZdPRuFQxLXEmBz1wOnFt1gwB1Tc/+KUyciYtsiGdfKDPZrr8JhHlMf1McJxc810jKFede0t/37GVCoLHc0MJSK+X3iXkW9atAc55Vu2TxZoxZU03/ItkJJAsBfaNZeg4z2klhPAdJGWpuHoGJT0eE/W04mZKbzJMir7qmS5a1qSyi5fxVV6pMoDicTosfQTaL7G7lBzSJTQ6xWRbZhxWpjkKNnIGK7ArYNkDD3tp9dhp3od+spLLcPuAul9RWMzqDhRuxBHzNkGRQjIcsBIBoZmGB4kVyrqS1MSWyeJOjLGVWIn7gfG3E2TtBtF/r9ujR2B3jCQOLAU1wuR/IoGeql0Nw1XTXJ7662idtRdKxkLIh3jLHZsT8yLyP7dlv9pRSc=}
provider:
  win: azure
conda_forge_output_validation: true
