travis:
  secure:
    BINSTAR_TOKEN: QA76dFDhXzuIfUgg9CSgJ3dN2QRmK9l/Qo/nnAY6RId1dFcqUSLvZqcGU0/ml5FEtCrTOmg7eZ0Cf+9BrKABbv9ANIxvD4DLDpjxdGFeS7QAQOLJFCPuy7exuch0YxtIjZE4LN5hAdiExxhDsGmJTNWpGyMAyV50QNkCoEP+zt2KxytP3EPiO+2baUhP4bdHcwqyDM4B1cpa8GkNgyWev4atLQv5IKlnYtnJr1ZcTSpxfzQHrfa42T6Vytp07eunMnNYWAnNTucNY8OSDIn8auT7Mj2racog+YYXGmtwjLL7NWR58rF5KPe6OloLQhMpyICzY20oAAG39fJU6mqVqakRBHJB+rKgHv+hTPZFLxzQMb17OzcMhcj/IMSzHWilQQbPMhkG816PzbyAOmOt+txhafrLQDxIa+FkM4f/PuqUGh7sCloyQANWCAbJa3rJrEfJX+PKJITyDIthae+bH3O2aCqIftvnF93uUmCdVQnB3B70qcV9ZzjOo9/YF2rxldidTrPcfmZoE9Yua73Fxk1T/+6v8xi7hSwSbAypzmXX7es9R73HxrKKNapwFf4u0lTTPdiQ6rkzvOtGz6p+dx4c3pX/aMdJ0yYWMZiuKHiOrKZ4yhkV8ZoagvubgsliKGGNYSKSilKk1VbAQx0e8z5k81z4so1IlTSIlyPR1lw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
channels:
  targets:
  - [conda-forge, rc]
conda_forge_output_validation: true
